name: Build Cross-Platform

on:
  push:
    paths:
      - .github/workflows/build.yml
      - src/**
      - src-tauri/**
      - package.json
  pull_request:
    paths:
      - .github/workflows/build.yml
      - src/**
      - src-tauri/**
      - package.json

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            build-args: --target x86_64-unknown-linux-gnu
            artifact-name: linux-x64
            artifact-path: |
              src-tauri/target/x86_64-unknown-linux-gnu/release/**/*.deb
              src-tauri/target/x86_64-unknown-linux-gnu/release/**/*.rpm
              src-tauri/target/x86_64-unknown-linux-gnu/release/**/*.AppImage
          - os: windows-latest
            build-args: ""
            artifact-name: windows-x64
            artifact-path: |
              src-tauri/target/release/bundle/**/*.exe
              src-tauri/target/release/bundle/**/*.msi
          - os: macos-latest
            build-args: ""
            artifact-name: macos
            artifact-path: src-tauri/target/release/bundle/macos/*
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt-get install -y pkg-config libwebkit2gtk-4.1-dev libgtk-3-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun tauri build ${{ matrix.platform.build-args }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.artifact-name }}
          path: ${{ matrix.platform.artifact-path }}
